
# The following redirect is intended for use with most SPAs
# that handle routing internally.

[[redirects]]

# home

[[redirects]]
  from = "https://gauge-io.webflow.io/"
  to = "/:splatâ€
  status = 200